---
- include_tasks: install.yml

- name: Create librespot audio cache directory
  file:
    path: "{{ librespot_cache_directory }}"
    state: directory
    owner: "{{ librespot_user }}"
  when: librespot_enable_cache

- name: Create librespot service
  template:
    src: librespot.service.j2
    dest: /etc/systemd/system/librespot.service
  notify:
    - Reload systemd configuration
    - Restart librespot service

- meta: flush_handlers

- name: Enable librespot service
  service:
    name: librespot
    enabled: True
    state: started
